import type { FastifyInstance } from 'fastify';
import { sql } from 'kysely';
import type {
  CreateAdjustmentRequest,
  CreateRateRequest,
  MemberBalanceResponse,
  RateResponse,
  StatementLine,
  StatementLineKind,
  StatementResponse,
} from '@flightsquare/shared';

import { ownMembership } from '../../db/membership.js';
import { ConflictError, InvalidRequestError, NotFoundError } from '../errors.js';
import type { Tx } from '../../db/context.js';

/**
 * Member billing (§3.7) — what a pilot owes their club.
 *
 * Behind `member_billing`, which is Pro and up: a free tenant has exactly one
 * member and so nobody to bill, and §1.6 makes a gated capability answer 404
 * rather than advertise itself. That is the opposite call from scheduling,
 * where §1 is explicit that one pilot means an empty table rather than a
 * switch — the difference is that an empty calendar is still a calendar,
 * while a ledger with one member in it is a category error.
 *
 * Almost nothing here writes. Charges are generated by a trigger when a
 * flight is logged, because a role that could write its own charges could
 * write a smaller one. What an admin can add is a correction — a reversing
 * entry with a reason — and an adjustment, which is how v1 records that
 * somebody paid.
 */

const feature = 'member_billing' as const;

const rateSchema = {
  body: {
    type: 'object',
    required: ['aircraft_id', 'amount_cents'],
    additionalProperties: false,
    properties: {
      aircraft_id: { type: 'string', format: 'uuid' },
      // §3.7 rule 3: integer minor units, at the boundary as everywhere else.
      amount_cents: { type: 'integer', minimum: 0 },
      effective_from: { type: 'string', format: 'date' },
      membership_id: { type: 'string', format: 'uuid' },
    },
  },
} as const;

const adjustmentSchema = {
  body: {
    type: 'object',
    required: ['membership_id', 'amount_cents', 'reason'],
    additionalProperties: false,
    properties: {
      membership_id: { type: 'string', format: 'uuid' },
      amount_cents: { type: 'integer' },
      reason: { type: 'string', minLength: 1, maxLength: 500 },
    },
  },
} as const;

const reverseSchema = {
  body: {
    type: 'object',
    required: ['reason'],
    additionalProperties: false,
    properties: { reason: { type: 'string', minLength: 1, maxLength: 500 } },
  },
} as const;

/**
 * A statement, assembled from three tables that never join.
 *
 * Charges, credits and adjustments are separate rows with separate rules —
 * one generated, one conditional on the rate basis, one hand-written — and
 * the statement is where they meet. Ordering is by when each happened, so it
 * reads the way the month did.
 */
async function statementFor(
  trx: Tx,
  membershipId: string,
  from: string | undefined,
  to: string | undefined,
): Promise<StatementResponse> {
  const member = await trx
    .selectFrom('memberships as m')
    .innerJoin('users as u', 'u.id', 'm.user_id')
    .select(['m.id', 'u.email', 'u.name'])
    .where('m.id', '=', membershipId)
    .executeTakeFirst();
  // Either no such membership, or one this viewer may not read — the policy
  // on `memberships` already decided, and §6 keeps the two answers the same.
  if (!member) throw new NotFoundError();

  const window = <T extends { created_at: Date }>(rows: T[]) =>
    rows.filter(
      (row) =>
        (!from || row.created_at >= new Date(from)) &&
        (!to || row.created_at < new Date(to)),
    );

  const [charges, credits, adjustments] = await Promise.all([
    trx
      .selectFrom('flight_charges as c')
      .leftJoin('flights as f', 'f.id', 'c.flight_id')
      .leftJoin('aircraft as a', 'a.id', 'f.aircraft_id')
      .select([
        'c.id',
        'c.flight_id',
        'c.amount_cents',
        'c.currency',
        'c.created_at',
        'c.meter',
        'c.meter_hours',
        'c.rate_cents',
        'c.rate_source',
        'c.reverses_id',
        'c.reason',
        'a.registration',
        'f.flight_date',
      ])
      .where('c.membership_id', '=', membershipId)
      .orderBy('c.created_at')
      .execute(),
    trx
      .selectFrom('fuel_credits as fc')
      .leftJoin('flights as f', 'f.id', 'fc.flight_id')
      .leftJoin('aircraft as a', 'a.id', 'f.aircraft_id')
      .select([
        'fc.id',
        'fc.flight_id',
        'fc.amount_cents',
        'fc.currency',
        'fc.created_at',
        'fc.quantity',
        'fc.reverses_id',
        'a.registration',
      ])
      .where('fc.membership_id', '=', membershipId)
      .orderBy('fc.created_at')
      .execute(),
    trx
      .selectFrom('ledger_adjustments')
      .select(['id', 'amount_cents', 'currency', 'created_at', 'reason'])
      .where('membership_id', '=', membershipId)
      .orderBy('created_at')
      .execute(),
  ]);

  // A row that something later reverses is marked rather than removed: both
  // halves stay on the statement, because that is what makes it explicable.
  const reversedCharges = new Set(charges.map((c) => c.reverses_id).filter(Boolean));
  const reversedCredits = new Set(credits.map((c) => c.reverses_id).filter(Boolean));

  const lines: StatementLine[] = [
    ...window(charges).map((c): StatementLine => ({
      id: c.id,
      kind: 'charge',
      occurred_at: c.created_at.toISOString(),
      description: c.reason
        ? c.reason
        : `${c.registration ?? 'Flight'}${c.flight_date ? ` on ${c.flight_date}` : ''}`,
      amount_cents: c.amount_cents,
      currency: c.currency,
      flight_id: c.flight_id,
      rate_source: c.rate_source,
      rate_cents: c.rate_cents,
      meter: c.meter,
      meter_hours: c.meter_hours,
      reversed: reversedCharges.has(c.id),
      reverses_id: c.reverses_id,
    })),
    ...window(credits).map((c): StatementLine => ({
      id: c.id,
      kind: 'credit',
      occurred_at: c.created_at.toISOString(),
      description: `Fuel${c.quantity ? ` — ${c.quantity}` : ''}${
        c.registration ? ` in ${c.registration}` : ''
      }`,
      // A credit reduces what is owed, so it carries the sign that makes the
      // column add up rather than needing a rule about how to read it.
      amount_cents: -c.amount_cents,
      currency: c.currency,
      flight_id: c.flight_id,
      rate_source: null,
      rate_cents: null,
      meter: null,
      meter_hours: null,
      reversed: reversedCredits.has(c.id),
      reverses_id: c.reverses_id,
    })),
    ...window(adjustments).map((a): StatementLine => ({
      id: a.id,
      kind: 'adjustment',
      occurred_at: a.created_at.toISOString(),
      description: a.reason,
      amount_cents: a.amount_cents,
      currency: a.currency,
      flight_id: null,
      rate_source: null,
      rate_cents: null,
      meter: null,
      meter_hours: null,
      reversed: false,
      reverses_id: null,
    })),
  ].sort((a, b) => a.occurred_at.localeCompare(b.occurred_at));

  const sum = (kind: StatementLineKind) =>
    lines.filter((line) => line.kind === kind).reduce((total, line) => total + line.amount_cents, 0);

  return {
    membership_id: member.id,
    email: member.email,
    name: member.name,
    from: from ?? null,
    to: to ?? null,
    lines,
    charged_cents: sum('charge'),
    credited_cents: -sum('credit'),
    adjusted_cents: sum('adjustment'),
    balance_cents: lines.reduce((total, line) => total + line.amount_cents, 0),
    currency: lines[0]?.currency ?? 'USD',
  };
}

export async function billingRoutes(app: FastifyInstance): Promise<void> {
  // -------------------------------------------------------------------------
  // Rates — the price list, and the private arrangements
  // -------------------------------------------------------------------------

  app.get<{ Querystring: { aircraft_id?: string } }>(
    '/rates',
    { config: { requiresTenant: true, feature, permission: ['rates', 'read'] } },
    async (request) => {
      const rows = await request.withTenant(async (trx) => {
        let club = trx
          .selectFrom('aircraft_rates as r')
          .innerJoin('aircraft as a', 'a.id', 'r.aircraft_id')
          .select([
            'r.id',
            'r.aircraft_id',
            'a.registration as aircraft_registration',
            'r.amount_cents',
            'r.currency',
            'r.effective_from',
          ]);
        if (request.query.aircraft_id) {
          club = club.where('r.aircraft_id', '=', request.query.aircraft_id);
        }
        return club.orderBy('a.registration').orderBy('r.effective_from', 'desc').execute();
      });
      return rows satisfies RateResponse[];
    },
  );

  /**
   * Member overrides, read through the `charges` scope rather than `rates`.
   *
   * What an aeroplane costs is the club's price list and everybody reads it.
   * What *Dave* pays for it is part of Dave's financial business, which is
   * exactly what §10 decision 3 protects — so the policy on the table gives
   * a pilot their own and gives the treasurer all of them, and this handler
   * does not have to know which.
   */
  app.get(
    '/member-rates',
    { config: { requiresTenant: true, feature, permission: ['rates', 'read'] } },
    async (request) => {
      const rows = await request.withTenant((trx) =>
        trx
          .selectFrom('member_aircraft_rates as r')
          .innerJoin('aircraft as a', 'a.id', 'r.aircraft_id')
          .innerJoin('memberships as m', 'm.id', 'r.membership_id')
          .innerJoin('users as u', 'u.id', 'm.user_id')
          .select([
            'r.id',
            'r.aircraft_id',
            'a.registration as aircraft_registration',
            'r.amount_cents',
            'r.currency',
            'r.effective_from',
            'r.membership_id',
            'u.email as member_email',
          ])
          .orderBy('u.email')
          .orderBy('r.effective_from', 'desc')
          .execute(),
      );
      return rows satisfies RateResponse[];
    },
  );

  app.post<{ Body: CreateRateRequest }>(
    '/rates',
    {
      schema: rateSchema,
      config: { requiresTenant: true, feature, permission: ['rates', 'write'] },
    },
    async (request, reply) => {
      const body = request.body;

      await request.withTenant(async (trx) => {
        const aircraft = await trx
          .selectFrom('aircraft')
          .select('id')
          .where('id', '=', body.aircraft_id)
          .executeTakeFirst();
        if (!aircraft) throw new NotFoundError();

        const createdBy = await ownMembership(trx, request.ctx!.userId);
        const row = {
          tenant_id: request.ctx!.tenantId!,
          aircraft_id: body.aircraft_id,
          amount_cents: body.amount_cents,
          created_by: createdBy,
          ...(body.effective_from ? { effective_from: body.effective_from } : {}),
        };

        // §3.7 rule 4: a change is a new row. There is no update path here
        // and no UPDATE grant behind it — history is what makes a statement
        // from March still readable in November.
        if (body.membership_id) {
          await trx
            .insertInto('member_aircraft_rates')
            .values({ ...row, membership_id: body.membership_id })
            .execute();
        } else {
          await trx.insertInto('aircraft_rates').values(row).execute();
        }
      });

      return reply.status(201).send({ status: 'recorded' });
    },
  );

  // -------------------------------------------------------------------------
  // Statements
  // -------------------------------------------------------------------------

  /**
   * One member's statement. Defaults to the caller's own, which is the only
   * one a Pilot can read anyway — the policy decides, not this handler.
   */
  app.get<{ Querystring: { member?: string; from?: string; to?: string } }>(
    '/statement',
    { config: { requiresTenant: true, feature, permission: ['charges', 'read'] } },
    async (request) => {
      return request.withTenant(async (trx) => {
        const membershipId =
          request.query.member ?? (await ownMembership(trx, request.ctx!.userId));
        return statementFor(trx, membershipId, request.query.from, request.query.to);
      });
    },
  );

  /** The treasurer's view. A Pilot sees exactly one row: their own. */
  app.get(
    '/balances',
    { config: { requiresTenant: true, feature, permission: ['charges', 'read'] } },
    async (request) => {
      const rows = await request.withTenant((trx) =>
        trx
          .selectFrom('memberships as m')
          .innerJoin('users as u', 'u.id', 'm.user_id')
          .select([
            'm.id as membership_id',
            'u.email',
            'u.name',
            // Three sums rather than a join: joining them would multiply the
            // rows against each other, which is the classic way to produce a
            // balance that is wrong by a factor nobody can explain.
            sql<string>`(
              coalesce((SELECT sum(c.amount_cents) FROM public.flight_charges c
                         WHERE c.membership_id = m.id), 0)
              - coalesce((SELECT sum(f.amount_cents) FROM public.fuel_credits f
                           WHERE f.membership_id = m.id), 0)
              + coalesce((SELECT sum(l.amount_cents) FROM public.ledger_adjustments l
                           WHERE l.membership_id = m.id), 0))`.as('balance_cents'),
          ])
          .where('m.status', '=', 'active')
          .orderBy('u.email')
          .execute(),
      );

      return rows.map(
        (row): MemberBalanceResponse => ({
          membership_id: row.membership_id,
          email: row.email,
          name: row.name,
          // bigint from the sums; a club's ledger is nowhere near unsafe.
          balance_cents: Number(row.balance_cents),
          currency: 'USD',
        }),
      );
    },
  );

  /**
   * §3.4's CSV, for member billing: the statement a treasurer pastes into
   * whatever they already use. V1_SCOPE keeps PDF and emailed statements out.
   */
  app.get<{ Querystring: { member?: string; from?: string; to?: string } }>(
    '/statement.csv',
    { config: { requiresTenant: true, feature, permission: ['charges', 'read'] } },
    async (request, reply) => {
      const statement = await request.withTenant(async (trx) => {
        const membershipId =
          request.query.member ?? (await ownMembership(trx, request.ctx!.userId));
        return statementFor(trx, membershipId, request.query.from, request.query.to);
      });

      const rows = [
        ['date', 'kind', 'description', 'meter', 'hours', 'rate', 'amount', 'currency'],
        ...statement.lines.map((line) => [
          line.occurred_at.slice(0, 10),
          line.kind,
          line.description,
          line.meter ?? '',
          line.meter_hours ?? '',
          // Money as a decimal string in the export, because that is what a
          // spreadsheet expects — converted once, at the boundary, from the
          // integer minor units everything else uses.
          line.rate_cents === null ? '' : (line.rate_cents / 100).toFixed(2),
          (line.amount_cents / 100).toFixed(2),
          line.currency,
        ]),
        [],
        ['', '', 'Balance', '', '', '', (statement.balance_cents / 100).toFixed(2), statement.currency],
      ];

      return reply
        .header('content-type', 'text/csv; charset=utf-8')
        .header('content-disposition', `attachment; filename="statement-${statement.email}.csv"`)
        .send(`${rows.map((row) => row.map(csvField).join(',')).join('\n')}\n`);
    },
  );

  // -------------------------------------------------------------------------
  // The two things an admin may write
  // -------------------------------------------------------------------------

  /**
   * §3.7 rule 2: a correction is a reversing entry plus, if needed, a new
   * charge. Never an edit — this is money, and it will be disputed.
   */
  app.post<{ Params: { id: string }; Body: { reason: string } }>(
    '/charges/:id/reverse',
    {
      schema: reverseSchema,
      config: { requiresTenant: true, feature, permission: ['charges', 'write'] },
    },
    async (request, reply) => {
      await request.withTenant(async (trx) => {
        const charge = await trx
          .selectFrom('flight_charges')
          .selectAll()
          .where('id', '=', request.params.id)
          .executeTakeFirst();
        if (!charge) throw new NotFoundError();
        if (charge.reverses_id) {
          throw new ConflictError('that entry is itself a reversal');
        }

        const already = await trx
          .selectFrom('flight_charges')
          .select('id')
          .where('reverses_id', '=', charge.id)
          .executeTakeFirst();
        if (already) throw new ConflictError('that charge has already been reversed');

        await trx
          .insertInto('flight_charges')
          .values({
            tenant_id: charge.tenant_id,
            flight_id: charge.flight_id,
            membership_id: charge.membership_id,
            meter: charge.meter,
            // The mirror image, so the pair nets to nothing and the
            // statement shows both halves of what happened.
            meter_hours: `-${charge.meter_hours}`,
            rate_cents: charge.rate_cents,
            rate_source: charge.rate_source,
            rate_basis: charge.rate_basis,
            amount_cents: -charge.amount_cents,
            currency: charge.currency,
            reverses_id: charge.id,
            reason: request.body.reason,
            created_by: await ownMembership(trx, request.ctx!.userId),
          })
          .execute();
      });

      return reply.status(201).send({ status: 'reversed' });
    },
  );

  /**
   * The only hand-written line, and in v1 the whole of how money moving is
   * recorded: "Dave paid $400 by cheque" is an adjustment.
   */
  app.post<{ Body: CreateAdjustmentRequest }>(
    '/adjustments',
    {
      schema: adjustmentSchema,
      config: { requiresTenant: true, feature, permission: ['charges', 'write'] },
    },
    async (request, reply) => {
      if (request.body.amount_cents === 0) {
        throw new InvalidRequestError('an adjustment of nothing is not an adjustment');
      }

      await request.withTenant(async (trx) => {
        await trx
          .insertInto('ledger_adjustments')
          .values({
            tenant_id: request.ctx!.tenantId!,
            membership_id: request.body.membership_id,
            amount_cents: request.body.amount_cents,
            reason: request.body.reason,
            created_by: await ownMembership(trx, request.ctx!.userId),
          })
          .execute();
      });

      return reply.status(201).send({ status: 'recorded' });
    },
  );
}

/** RFC 4180: quote anything containing a comma, quote or newline. */
function csvField(value: string): string {
  return /[",\n\r]/.test(value) ? `"${value.replaceAll('"', '""')}"` : value;
}
